import Nav from './components/nav'
import { Poppins } from "@next/font/google"
import './globals.css'

const font=Poppins({
  weight: ["400","700"],
  subsets: ["latin"],
  variable: "--font-poppins"
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={font.className}>
      <Nav />
      {children}
      </body>
    </html>
  )
}
